#!/bin/bash
# RealtySarv Firebase Initialization Guide
# This script documents how to initialize Firestore collections and indexes

echo "════════════════════════════════════════════════════════════════"
echo "    RealtySarv Firebase & Firestore Initialization Guide"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📋 PROJECT DETAILS"
echo "══════════════════════════════════════════════════════════════════"
echo "Firebase Project ID:      gen-lang-client-0873542795"
echo "Firestore Database ID:    ai-studio-10a71e0e-6277-4ebb-b538-3263c6ea0ada"
echo "Auth Domain:              gen-lang-client-0873542795.firebaseapp.com"
echo "Storage Bucket:           gen-lang-client-0873542795.firebasestorage.app"
echo ""

echo "🚀 INITIALIZATION OPTIONS"
echo "══════════════════════════════════════════════════════════════════"
echo ""

echo "Option 1: Automated TypeScript Script"
echo "────────────────────────────────────"
echo "Command:"
echo "  npx ts-node firestore-init.ts"
echo ""
echo "This will:"
echo "  ✓ Create all 13 Firestore collections"
echo "  ✓ Add sample documents to each collection"
echo "  ✓ Verify collections exist"
echo "  ✓ Demonstrate common Firestore queries"
echo ""

echo "Option 2: Firebase CLI"
echo "────────────────────"
echo "1. Install Firebase CLI:"
echo "   npm install -g firebase-tools"
echo ""
echo "2. Login to Firebase:"
echo "   firebase login"
echo ""
echo "3. Initialize Firebase in project:"
echo "   firebase init"
echo ""
echo "4. Deploy Firestore indexes:"
echo "   firebase deploy --only firestore:indexes --config firebase-indexes.json"
echo ""

echo "Option 3: Manual via Firebase Console"
echo "────────────────────────────────────"
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Select Project: gen-lang-client-0873542795"
echo "3. Navigate to: Firestore Database"
echo "4. Create collections with these IDs:"
echo ""
echo "   Collections to Create:"
echo "   ├── companies"
echo "   ├── users"
echo "   ├── projects"
echo "   ├── leads"
echo "   ├── tasks"
echo "   ├── siteVisits"
echo "   ├── bookings"
echo "   ├── agreements"
echo "   ├── ledgers"
echo "   ├── vouchers"
echo "   ├── templates"
echo "   ├── channelPartners"
echo "   ├── integrations"
echo "   └── settings"
echo ""

echo "🔍 FIRESTORE INDEXES TO CREATE"
echo "══════════════════════════════════════════════════════════════════"
echo ""

echo "Auto-created by deploying firebase-indexes.json:"
echo ""
echo "Leads Indexes:"
echo "  ✓ companyId + leadStatus + createdAt (DESC)"
echo "  ✓ companyId + ownerId + createdAt (DESC)"
echo ""

echo "Tasks Indexes:"
echo "  ✓ companyId + assignedTo + status + dueDate"
echo "  ✓ companyId + leadId + createdAt (DESC)"
echo ""

echo "Bookings Indexes:"
echo "  ✓ companyId + projectId + status"
echo "  ✓ companyId + leadId"
echo ""

echo "Site Visits Indexes:"
echo "  ✓ companyId + leadId + scheduledDate"
echo "  ✓ companyId + projectId + status"
echo ""

echo "Vouchers Indexes:"
echo "  ✓ companyId + date (DESC)"
echo "  ✓ companyId + type + status"
echo ""

echo "Users Indexes:"
echo "  ✓ companyId + role + isActive"
echo ""

echo "Projects Indexes:"
echo "  ✓ companyId + projectStatus + createdAt (DESC)"
echo ""

echo "Channel Partners Indexes:"
echo "  ✓ companyId + status"
echo ""

echo "📊 FIRESTORE COLLECTIONS SCHEMA"
echo "══════════════════════════════════════════════════════════════════"
echo ""

echo "1. companies"
echo "   ├── companyId (string)"
echo "   ├── name (string)"
echo "   ├── address (string)"
echo "   ├── phone (string)"
echo "   ├── website (string)"
echo "   ├── logoUrl (string, optional)"
echo "   ├── setupCompleted (boolean)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "2. users"
echo "   ├── userId (string)"
echo "   ├── email (string)"
echo "   ├── name (string)"
echo "   ├── phone (string)"
echo "   ├── role (string: Admin|Sales|Manager|User)"
echo "   ├── designation (string)"
echo "   ├── isActive (boolean)"
echo "   ├── companyId (string)"
echo "   ├── assignedProjectIds (array)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "3. projects"
echo "   ├── projectId (string)"
echo "   ├── companyId (string)"
echo "   ├── name (string)"
echo "   ├── location (string)"
echo "   ├── reraNumber (string)"
echo "   ├── projectType (string)"
echo "   ├── projectStatus (string)"
echo "   ├── description (string)"
echo "   ├── totalFloors (number)"
echo "   ├── wings (array of objects)"
echo "   ├── inventory (array of objects)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "4. leads"
echo "   ├── leadId (string)"
echo "   ├── companyId (string)"
echo "   ├── name (string)"
echo "   ├── email (string)"
echo "   ├── phone (string)"
echo "   ├── leadStatus (string)"
echo "   ├── bookingStatus (string)"
echo "   ├── agreementStatus (string)"
echo "   ├── possessionStatus (string)"
echo "   ├── channelSource (string)"
echo "   ├── leadSource (string)"
echo "   ├── budget (string)"
echo "   ├── projectOfInterest (string)"
echo "   ├── ownerId (string - FK to users)"
echo "   ├── messages (array)"
echo "   ├── siteVisits (array)"
echo "   ├── tasks (array)"
echo "   ├── propertyImages (array)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "5. tasks"
echo "   ├── taskId (string)"
echo "   ├── companyId (string)"
echo "   ├── leadId (string - FK to leads)"
echo "   ├── title (string)"
echo "   ├── description (string)"
echo "   ├── dueDate (date)"
echo "   ├── priority (string: Low|Medium|High|Critical)"
echo "   ├── status (string: Pending|Completed|Overdue)"
echo "   ├── assignedTo (string - FK to users)"
echo "   ├── createdBy (string - FK to users)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "6. siteVisits"
echo "   ├── visitId (string)"
echo "   ├── companyId (string)"
echo "   ├── leadId (string - FK to leads)"
echo "   ├── projectId (string - FK to projects)"
echo "   ├── scheduledDate (timestamp)"
echo "   ├── completedDate (timestamp, optional)"
echo "   ├── status (string: Scheduled|Completed|Cancelled)"
echo "   ├── notes (string)"
echo "   ├── attendees (array of user IDs)"
echo "   ├── feedback (string)"
echo "   ├── rating (number)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "7. bookings"
echo "   ├── bookingId (string)"
echo "   ├── companyId (string)"
echo "   ├── leadId (string - FK to leads)"
echo "   ├── projectId (string - FK to projects)"
echo "   ├── unitId (string)"
echo "   ├── status (string: Pending|Booked|Cancelled)"
echo "   ├── tokenAmount (number)"
echo "   ├── registrationAmount (number)"
echo "   ├── totalAmount (number)"
echo "   ├── paymentSchedule (array)"
echo "   ├── possessionDate (date)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "8. agreements"
echo "   ├── agreementId (string)"
echo "   ├── companyId (string)"
echo "   ├── bookingId (string - FK to bookings)"
echo "   ├── leadId (string - FK to leads)"
echo "   ├── status (string: Drafted|Sent|Signed|Registered)"
echo "   ├── content (string - PDF/HTML content)"
echo "   ├── signatories (array)"
echo "   ├── signedDate (date)"
echo "   ├── registrationNumber (string)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "9. ledgers"
echo "   ├── ledgerId (string)"
echo "   ├── companyId (string)"
echo "   ├── accountName (string)"
echo "   ├── accountCode (string)"
echo "   ├── group (string: Assets|Liabilities|Income|Expenses|Equity)"
echo "   ├── openingBalance (number)"
echo "   ├── currentBalance (number)"
echo "   ├── isSystem (boolean)"
echo "   ├── createdAt (timestamp)"
echo "   └── updatedAt (timestamp)"
echo ""

echo "10. vouchers"
echo "    ├── voucherId (string)"
echo "    ├── companyId (string)"
echo "    ├── voucherNumber (string)"
echo "    ├── date (date)"
echo "    ├── type (string: Journal|Payment|Receipt|Contra|Sales|Purchase)"
echo "    ├── entries (array of objects)"
echo "    ├── narration (string)"
echo "    ├── projectId (string, optional)"
echo "    ├── bookingId (string, optional)"
echo "    ├── status (string: Draft|Posted|Cancelled)"
echo "    ├── createdAt (timestamp)"
echo "    └── updatedAt (timestamp)"
echo ""

echo "11. templates"
echo "    ├── templateId (string)"
echo "    ├── companyId (string)"
echo "    ├── name (string)"
echo "    ├── type (string: WhatsApp|Email|SMS)"
echo "    ├── content (string)"
echo "    ├── createdAt (timestamp)"
echo "    └── updatedAt (timestamp)"
echo ""

echo "12. channelPartners"
echo "    ├── partnerId (string)"
echo "    ├── companyId (string)"
echo "    ├── firmName (string)"
echo "    ├── contactPerson (string)"
echo "    ├── email (string)"
echo "    ├── phone (string)"
echo "    ├── reraNumber (string)"
echo "    ├── status (string: Active|Inactive|Pending)"
echo "    ├── commissionRate (number)"
echo "    ├── totalLeads (number)"
echo "    ├── totalConversions (number)"
echo "    ├── onboardingDate (date)"
echo "    ├── createdAt (timestamp)"
echo "    └── updatedAt (timestamp)"
echo ""

echo "13. integrations & settings"
echo "    └── (Schema varies per integration type)"
echo ""

echo "✅ RECOMMENDED INITIALIZATION SEQUENCE"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Initialize databases (if not done):"
echo "   cd server && npm run db:setup"
echo ""
echo "2. Initialize Firestore collections:"
echo "   npx ts-node firestore-init.ts"
echo ""
echo "3. Deploy Firestore indexes:"
echo "   firebase deploy --only firestore:indexes --config firebase-indexes.json"
echo ""
echo "4. Start the application:"
echo "   Terminal 1: npm run dev (frontend on :3000)"
echo "   Terminal 2: cd server && npm run dev (backend on :4000)"
echo ""

echo "🔐 FIRESTORE SECURITY RULES"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "See: firestore.rules"
echo ""
echo "Key features:"
echo "  ✓ Company-level data isolation"
echo "  ✓ User authentication required"
echo "  ✓ Role-based access control"
echo "  ✓ Field-level security"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ Firebase Setup Complete!"
echo "════════════════════════════════════════════════════════════════"
